config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "home#index"

  resources :companies, only: [:show, :index] do
    get 'search', on: :collection
  end
  resources :company_card_types, only: [:create, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :card_types, only: [:index, :new, :create, :show, :edit, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :payments, only: [] do
    get 'search_pending', on: :collection
    get 'search_ended', on: :collection
    patch 'approve', on: :member
    patch 'reprove', on: :member
    get 'pending', on: :collection
    get 'finished', on: :collection
  end

  resources :cashback_rules, only: [:index, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :company_card_types, only: [:index]
      resources :extracts, only: [:index]
      resources :payments, only: [:create, :show] do
        get 'by_cpf', on: :collection, to: 'payments#all_by_cpf'
      end
      resources :cards, only: [:create, :destroy, :show] do
        delete 'block', on: :member
        patch 'activate', on: :member
        patch 'deactivate', on: :member
        post 'upgrade', on: :collection
        patch 'recharge', on: :collection, to: 'recharges#update'
      end
    end
  end
end

app/models/company.rb
class Company
  attr_accessor :id, :brand_name, :registration_number, :active

  def initialize(id:, brand_name:, registration_number:, active:)
    @id = id
    @brand_name = brand_name
    @registration_number = registration_number
    @active = active
  end

  def self.all(search_query = nil)
    response = Faraday.get('http://localhost:3000/api/v1/companies')
    companies = []
    if response.status == 200
      data = JSON.parse(response.body)
      companies = build_companies(data, search_query)
    end
    companies
  rescue Faraday::ConnectionFailed
    raise CompanyConnectionError
  end

  def self.find(id)
    response = Faraday.get("http://localhost:3000/api/v1/companies/#{id}")

    return unless response.status == 200

    data = JSON.parse(response.body)

    build_company(data)
  rescue Faraday::ConnectionFailed
    raise CompanyConnectionError
  end

  def matches_search?(search_query)
    return true if search_query.empty?

    regex = /#{Regexp.escape(search_query)}/i
    brand_name.match?(regex) || registration_number.match?(regex)
  end

  class << self
    private

    def build_company(data)
      Company.new(id: data['id'], brand_name: data['brand_name'],
                  registration_number: data['registration_number'], active: data['active'])
    end

    def build_companies(data, search_query)
      companies = []
      data.each do |d|
        company = build_company(d)
        companies << company if search_query.nil? || company.matches_search?(search_query)
      end
      companies
    end
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    companies_data = Company.all
    @companies = companies_data.filter { |c| c.active == true }
  end

  def search
    search = params[:search]
    companies_data = Company.all(search)
    @companies = companies_data.filter { |c| c.active == true }
  end

  def show
    @company = Company.find(params[:id])
    redirect_to companies_path, notice: I18n.t('.companies.index.inactive_company') unless @company.active
    @card_types = CardType.enabled
    @company_card_types = CompanyCardType.where(cnpj: @company.registration_number)
    @linked_card_types = @company_card_types.to_a.map(&:card_type)
    @cashback_rules = CashbackRule.order(:minimum_amount_points)
  end
end

app/views/companies/_index.html.erb
<nav aria-label="breadcrumb" >
  <ol class="breadcrumb" >
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.companies') %></li>
  </ol>
</nav>

<%= render partial: 'shared/search_bar', locals: {i18n_path: 'companies.index.provide_card_types', especific_search_path: search_companies_path,
                                                                 placeholder: 'Pesquisar pelo nome ou cnpj', search: search }%>

<section class='d-flex flex-column gap-3'>
  <% if @companies.present? %>
    <% @companies.each do |company| %>
      <%= link_to company_path(company.id), id: company.id, class: 'company-card' do %>
        <span class='company-name'><%= company.brand_name %></span>
        <span class='company-registration-number'><%= t('.registration_number') %>: <%= cnpj_formatter(company.registration_number) %></span>
      <% end %>
    <% end %> 
  <% else %>
    <p><%= t('.not_found_message') %></p>
  <% end %>
</section>

app/views/companies/_linked_card_type.html.erb
<div class='linked'>
  <div class='card-section'>
    <%= image_tag card_type.icon, alt: card_type.name, class: 'card-icon' %>

    <div class='card-info'>
      <span class='title'><%= card_type.name %></span>

      <% status_color = company_card_type.active? ? 'text-primary' : 'text-danger' %>
      <span class=<%= status_color %>><%= CompanyCardType.human_attribute_name("status.#{company_card_type.status}") %></span>
    </div>
  </div>

  <% if company_card_type.active? %>
    <%= button_to t('.inactivate_card_type'), disable_company_card_type_path,
        method: :patch, class: 'btn btn-danger btn-company-card-type',
        params: params %>
  <% else %>
    <%= button_to t('.activate_card_type'), enable_company_card_type_path,
        method: :patch, class: 'btn btn-primary btn-company-card-type',
        params: params %>
  <% end %>
</div>

<%= form_with model: company_card_type do |f| %>
  <div class='w-100'>
    <%= f.label :cashback_rule_id %>
    <%= f.collection_select :cashback_rule_id, @cashback_rules, :id, :description, { include_blank: t('.choose_cashback_rule') }, {data: {controller: 'slim'}} %>
  </div>

  <div class='w-50'>
    <%= f.label :conversion_tax %>
    <%= f.number_field :conversion_tax, step: 0.01, placeholder: t('.whats_the_conversion_tax') %>
  </div>

  <%= f.hidden_field :card_type_id, value: card_type.id %>
  <%= f.hidden_field :cnpj, value: @company.registration_number %>
  <%= hidden_field_tag :company_id, @company.id %>
  
  <%= f.submit t('.save_rule_and_tax'), class: 'btn btn-secondary btn-company-card-type' %>

<% end %>

app/views/companies/_unlinked_card_type.html.erb
<div class='card-section'>
  <%= image_tag card_type.icon, alt: card_type.name, class: 'card-icon' %>

  <div class='card-info'>
    <span class='title'><%= card_type.name %></span>
    <span class='unlinked-color'><%= CompanyCardType.human_attribute_name("status.unlinked") %></span>
  </div>
</div>

<%= form_with url: company_card_types_path, scope: :company_card_type do |f| %>
  <div class='w-100'>
    <%= f.label :cashback_rule_id, t('.cashback_rule') %>
    <%= f.collection_select :cashback_rule_id, @cashback_rules, :id, :description, { include_blank: t('.choose_cashback_rule') }, {data: {controller: 'slim'}} %>
  </div>

  <div class='w-50'>
    <%= f.label :conversion_tax, t('.conversion_tax') %>
    <%= f.number_field :conversion_tax, step: 0.01, placeholder: t('.whats_the_conversion_tax') %>
  </div>

  <%= f.hidden_field :card_type_id, value: card_type.id %>
  <%= f.hidden_field :cnpj, value: @company.registration_number %>
  <%= hidden_field_tag :company_id, @company.id %>
  
  <%= f.submit t('.link_company'), class: 'btn btn-success btn-company-card-type' %>
<% end %>

app/views/companies/index.html.erb
<%= render partial: 'index', locals: { companies: @companies, search: false }%>

app/views/companies/search.html.erb
<%= render partial: 'index', locals: { companies: @companies, search: true }%>

app/views/companies/show.html.erb
<nav aria-label="breadcrumb" >
  <ol class="breadcrumb" >
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.companies'), companies_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.card_types') %></li>
  </ol>
</nav>

<div class='company-header'>
  <h1 class='title-style m-0'><%= @company.brand_name %></h1>
  <h2><%= t('.registration_number') %>: <%= cnpj_formatter(@company.registration_number) %></h2>
</div>

<section class='d-flex flex-column gap-3'>
  <% if @card_types.blank? %>
    <p><%= t('.no_card_type_with_issuance_enabled') %></p>
  <% else %>
    <% @card_types.each do |card_type| %>
      <div id=<%= dom_id(card_type) %> class='company-types-card'>
        <% params = { company_id: @company.id, company_card_type: {
                      card_type_id: card_type.id, cnpj: @company.registration_number } } %>

        <% if @linked_card_types.include? card_type %>
          <% company_card_type = @company_card_types.find { |company_card_type| company_card_type.card_type == card_type } %>

          <%= render partial: 'linked_card_type', locals: { company_card_type:, card_type:, params: } %>
        <% else %>
          <%= render partial: 'unlinked_card_type', locals: { card_type: } %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</section>