config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "home#index"

  resources :companies, only: [:show, :index] do
    get 'search', on: :collection
  end
  resources :company_card_types, only: [:create, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :card_types, only: [:index, :new, :create, :show, :edit, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :payments, only: [] do
    get 'search_pending', on: :collection
    get 'search_ended', on: :collection
    patch 'approve', on: :member
    patch 'reprove', on: :member
    get 'pending', on: :collection
    get 'finished', on: :collection
  end

  resources :cashback_rules, only: [:index, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :company_card_types, only: [:index]
      resources :extracts, only: [:index]
      resources :payments, only: [:create, :show] do
        get 'by_cpf', on: :collection, to: 'payments#all_by_cpf'
      end
      resources :cards, only: [:create, :destroy, :show] do
        delete 'block', on: :member
        patch 'activate', on: :member
        patch 'deactivate', on: :member
        post 'upgrade', on: :collection
        patch 'recharge', on: :collection, to: 'recharges#update'
      end
    end
  end
end

app/controllers/card_types_controller.rb
class CardTypesController < ApplicationController
  def index
    @card_types = CardType.all
    @cards_emission_enabled = CardType.enabled
    @cards_emission_disabled = CardType.disabled
  end

  def show
    @card_type = CardType.find(params[:id])
  end

  def new
    @card_type = CardType.new
  end

  def edit
    @card_type = CardType.find(params[:id])
  end

  def create
    @card_type = CardType.new(card_type_params)
    return redirect_to card_type_path(@card_type), notice: I18n.t('notices.card_type_created') if @card_type.save

    flash.now.alert = I18n.t('.alerts.failed_to_create_card_type')
    render :new, status: :unprocessable_entity
  end

  def update
    @card_type = CardType.find(params[:id])
    return redirect_to @card_type, notice: I18n.t('notices.card_type_updated') if @card_type.update(card_type_params)

    flash.now.alert = I18n.t('alerts.card_type_changes_not_saved')
    render :edit, status: :unprocessable_entity
  end

  def disable
    @card_type = CardType.find(params[:id])
    @card_type.emission = false
    @card_type.save!
    @card_type.company_card_types.each(&:inactive!)

    redirect_to @card_type, notice: I18n.t('notices.card_type_disabled')
  end

  def enable
    @card_type = CardType.find(params[:id])
    @card_type.emission = true
    @card_type.save!

    redirect_to @card_type, notice: I18n.t('notices.card_type_enabled')
  end

  private

  def card_type_params
    params.require(:card_type).permit(:name, :icon, :start_points)
  end
end

app/views/card_types/_errors_full_messages.erb
<% if @card_type.errors.present? %>
  <h4><%=t('.check_errors')%>:</h4>
  <div id='errors-div'>
    <% @card_type.errors.full_messages.each do |message| %>
      <span><%= message %></span>
    <% end %>
  </div>
<% end %>

app/views/card_types/_form.html.erb
<%= form_with model: @card_type, class: 'form' do |f| %>
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name %>
      <% if @card_type.errors.where(:name) %>
        <% @card_type.errors.where(:name).each do |e| %>
          <span class='text-danger errors'><%= "#{CardType.human_attribute_name(e.attribute)} #{e.message}" %></span>
        <% end %>
      <% end %>
  </div>

  <div class='field'>
    <%= f.label :start_points %>
    <%= f.number_field :start_points %>
    <% if @card_type.errors.where(:start_points) %>
        <% @card_type.errors.where(:start_points).each do |e| %>
          <span class='text-danger errors'><%= "#{CardType.human_attribute_name(e.attribute)} #{e.message}" %></span>
        <% end %>
    <% end %>
  </div>

  <div class='field' data-controller='preview'>
    <%= f.label :icon %>
    <%= f.label :icon, class: 'w-100' do %>
      <div class='image-area'>
        <i data-preview-target='picturePlaceholder' class="bi bi-image-fill picture-icon"></i>
        <span data-preview-target='textPlaceholder'><%= t('.select_image_placeholder') %></span>
        <%= image_tag '', data: { preview_target: 'output' }, class: 'image-preview' %>
      </div>
    <% end %>
    <%= f.file_field :icon, class: 'd-none', data: { preview_target: 'input', action:'preview#readURL' }, accept: 'image/jpeg, image/gif, image/png, image/svg+xml' %>
    <% if @card_type.errors.where(:icon) %>
        <% @card_type.errors.where(:icon).each do |e| %>
          <span class='text-danger errors'><%= "#{CardType.human_attribute_name(e.attribute)} #{e.message}" %></span>
        <% end %>
    <% end %>
  </div>

  <%= f.submit t('.save_type'), class: 'btn btn-primary btn-submit' %>
<% end %>

app/views/card_types/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.card_types'), card_types_path %></li>
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.card', name: @card_type.name), card_type_path(@card_type) %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.edit_card_type') %></li>
  </ol>
</nav>

<section id='card-type-form'>
  <h1 class='title-style'><%= t('.edit_card_type') %></h1>
  <%= render 'form'%>
</section>

app/views/card_types/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.card_types') %></li>
  </ol>
</nav>

<section class='emissions'>
  <div id='emission-enabled-card-types'>
    <h1 class='title-style'><%= t('.types_enabled_for_issuance') %></h1>

    <% if @cards_emission_enabled.empty? %>
      <span><%= t('.no_card_type_with_issuance_enabled') %></span>
    <% else %>
      <div class='card-type-list'>
        <% @cards_emission_enabled.each do |type|%>
          <%= link_to type, class: 'index-card-type' do %>
            <%= image_tag type.icon, alt: t('.card_type_icon', name: type.name), class: 'card-icon' %>
            <span class='card-type-name'><%= t('.card', name: type.name) %></span>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div id='emission-disabled-card-types'>
    <h1 class='title-style'><%= t('.types_disabled_for_issuance') %></h1>
    <% if @cards_emission_disabled.empty? %>
      <span><%= t('.no_card_type_with_issuance_disabled') %></span>
    <% else %>
      <div class='card-type-list'>
        <% @cards_emission_disabled.each do |type|%>
          <%= link_to type, class: 'index-card-type' do %>
            <%= image_tag type.icon, alt: t('.card_type_icon', name: type.name), class: 'card-icon' %>
            <span class='card-type-name'><%= t('.card', name: type.name) %></span>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/card_types/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.new_card_type') %></li>
  </ol>
</nav>

<h1 class='title-style'><%= t('.new_card_type') %></h1>
<%= render 'form'%>

app/views/card_types/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.card_types'), card_types_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.card', name: @card_type.name) %></li>
  </ol>
</nav>

<section class='show-card-type'>
  <h1 class='title-style m-0'><%= t('.card', name: @card_type.name) %></h1>

  <% if @card_type.icon.attached? %>
    <%= image_tag @card_type.icon, alt: "Ícone cartão #{@card_type.name}", class: 'w-100' %>
  <% end %>
  
  <div class='body'>
    <span class='card-text'><%= t('.initial_points') %></span>
    <span class='card-text'><%= t('.points', points: @card_type.start_points) %></span>
  </div>
  
  <div class='card-footer w-100'>
    <%=link_to 'Editar', edit_card_type_path(@card_type), class: 'btn btn-secondary btn-show-card-type w-25'%>
    <% if @card_type.emission %>
      <%= button_to 'Desabilitar emissão', disable_card_type_path(@card_type), form_class: 'w-75', class: 'btn btn-danger btn-show-card-type', method: :patch %>
    <% else %>
      <%= button_to 'Habilitar emissão', enable_card_type_path(@card_type), form_class: 'w-75', class: 'btn btn-success btn-show-card-type', method: :patch %>
    <% end %>
  </div>
</section>