config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "home#index"

  resources :companies, only: [:show, :index] do
    get 'search', on: :collection
  end
  resources :company_card_types, only: [:create, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :card_types, only: [:index, :new, :create, :show, :edit, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :payments, only: [] do
    get 'search_pending', on: :collection
    get 'search_ended', on: :collection
    patch 'approve', on: :member
    patch 'reprove', on: :member
    get 'pending', on: :collection
    get 'finished', on: :collection
  end

  resources :cashback_rules, only: [:index, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :company_card_types, only: [:index]
      resources :extracts, only: [:index]
      resources :payments, only: [:create, :show] do
        get 'by_cpf', on: :collection, to: 'payments#all_by_cpf'
      end
      resources :cards, only: [:create, :destroy, :show] do
        delete 'block', on: :member
        patch 'activate', on: :member
        patch 'deactivate', on: :member
        post 'upgrade', on: :collection
        patch 'recharge', on: :collection, to: 'recharges#update'
      end
    end
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  include ReaisToPointsConversionHelper
  include QueryValidCashbackHelper
  has_many :errors_associations, dependent: :restrict_with_exception
  enum status: { pending: 0, approved: 3, rejected: 5, pre_approved: 2, pre_rejected: 4 }

  validates :order_number, :total_value, :descount_amount, :final_value,
            :card_number, :cpf, :status, :code, :payment_date, presence: true
  validates :code, uniqueness: true
  validates :code, length: { is: 10 }

  before_validation :generate_code, on: :create
  after_create :pre_approve

  def formatted_card_number
    card_number.gsub(/(\d{4})(\d{4})(\d{4})(\d{4})(\d{4})/, '\1 \2 \3 \4 \5')
  end

  def format_cpf(cpf)
    cpf.gsub(/\A(\d{3})(\d{3})(\d{3})(\d{2})\Z/, '\\1.\\2.\\3-\\4')
  end

  def format_money(value)
    format('%.2f', value).sub('.', ',')
  end

  def check_balance(card_number)
    Card.find_by(number: card_number).points
  end

  def get_final_balance(payment)
    card = Card.find_by(number: payment.card_number)
    points = check_balance(card_number)
    points - reais_to_points(card, final_value)
  end

  def subtract_cashback_if_possible(card, cashback)
    new_final_value = reais_to_points(card, final_value)
    new_final_value -= cashback.amount if cashback.present?
    new_final_value
  end

  def process_payment_approval(card, cashback, final_value)
    ActiveRecord::Base.transaction do
      debit_points(card, cashback, final_value, self)
      Extract.create!(date: payment_date, operation_type: 'débito', value: final_value,
                      description: "Pedido #{order_number}", card_number: card.number)
      next true if card.company_card_type.cashback_rule.blank?

      Cashback.create_cashback_if_possible(final_value, card, self)
      true
    rescue ActiveRecord::RecordInvalid
      false
    end
  end

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end

  def check_card_valid
    card = Card.find_by(number: card_number)
    if card.nil?
      ErrorsAssociation.create(payment_id: id, error_message_id: 1)
      return false
    end
    true
  end

  def pre_approve
    card = Card.find_by(number: card_number)
    c_cv = check_card_valid
    if c_cv
      c_cpf = check_cpf(card.cpf, cpf)
      c_cs = check_status(card.status)
      c_cb = check_card_balance(card, final_value)
      return pre_approved! if c_cpf && c_cs && c_cb
    end
    pre_rejected!
  end

  def check_status(status)
    if status != 'active'
      ErrorsAssociation.create(payment_id: id, error_message_id: 2)
      return false
    end
    true
  end

  def check_cpf(card_cpf, order_cpf)
    if card_cpf != order_cpf
      ErrorsAssociation.create(payment_id: id, error_message_id: 3)
      return false
    end
    true
  end

  def check_card_balance(card, value)
    conversion_for_points = reais_to_points(card, value)
    cashback = query_valid_cashback(cpf)
    conversion_for_points -= cashback.amount if cashback.present?
    return true if card.points >= conversion_for_points

    false if ErrorsAssociation.create(payment_id: id, error_message_id: 4)
  end

  def debit_points(card, cashback, final_value, payment)
    cashback.change_cashback_used(payment, card) if cashback.present?
    card.points -= final_value
    card.save!
    approved!
  end
end

app/controllers/api/v1/payments_controller.rb
class Api::V1::PaymentsController < Api::V1::ApiController
  def show
    payment = Payment.find_by!(code: params[:id])
    json_payment = format_created_payment(payment)
    render status: :ok, json: json_payment
  end

  def create
    payment_params = params.require(:payment).permit(:order_number, :total_value, :descount_amount, :final_value,
                                                     :cpf, :card_number, :payment_date)
    payment = Payment.new(payment_params)

    if payment.save
      render status: :created, json: format_created_payment(payment)
    else
      render status: :precondition_failed, json: { errors: payment.errors.full_messages }
    end
  end

  def all_by_cpf
    Card.find_by!(cpf: params[:cpf])
    payments = Payment.where(cpf: params[:cpf])
    json_payments = format_created_payments(payments)
    render status: :ok, json: json_payments
  end

  private

  def format_created_payments(payments)
    payments.map do |payment|
      format_created_payment(payment)
    end
  end

  def format_created_payment(payment)
    { order_number: payment.order_number,
      total_value: payment.total_value,
      descount_amount: payment.descount_amount,
      final_value: payment.final_value,
      cpf: payment.cpf,
      card_number: payment.card_number,
      payment_date: payment.payment_date,
      status: payment.status == 'pre_rejected' || payment.status == 'pre_approved' ? :pending : payment.status,
      code: payment.code,
      error: payment.status == 'rejected' ? 'O pagamento não pode ser concluído, contate a aplicação de cartões' : '' }
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include QueryValidCashbackHelper
  include ReaisToPointsConversionHelper
  def pending
    @pre_approved = Payment.pre_approved
    @pre_reproved = Payment.pre_rejected
  end

  def finished
    @finished_payments = Payment.where('status = 3 or status = 5').order(updated_at: :desc)
  end

  def approve
    payment = Payment.find(params[:id])
    card = get_payment_card(payment)
    cashback = query_valid_cashback(payment.cpf)
    final_value = payment.subtract_cashback_if_possible(card, cashback)

    if card.can_approve_payment?(final_value) && payment.process_payment_approval(card, cashback, final_value)
      return redirect_to pending_payments_path, notice: I18n.t('notices.payment_approved')

    end

    redirect_to pending_payments_path, alert: I18n.t('alerts.payment_approved_error')
  end

  def reprove
    payment = Payment.find(params[:id])

    payment.rejected!
    ErrorsAssociation.create(payment_id: payment.id, error_message_id: 5)
    redirect_to pending_payments_path, notice: I18n.t('notices.payment_rejected')
  end

  def search_pending
    search = params[:search]
    @pre_approved = Payment.where('(order_number LIKE ? OR cpf LIKE ?) AND (status = 2)', "%#{search}%",
                                  "%#{search}%")
    @pre_reproved = Payment.where('(order_number LIKE ? OR cpf LIKE ?) AND (status = 4)', "%#{search}%",
                                  "%#{search}%")
  end

  def search_ended
    search = params[:search]
    @finished_payments = Payment.where('(order_number LIKE ? OR cpf LIKE ?) AND (status = 3 OR status = 5)',
                                       "%#{search}%", "%#{search}%")
  end

  private

  def get_payment_card(payment)
    Card.find_by(number: payment.card_number)
  end
end

app/views/payments/_finished.html.erb
<nav aria-label="breadcrumb" >
  <ol class="breadcrumb" >
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.finished_payments') %></li>
  </ol>
</nav>

<%= render partial: 'shared/search_bar', locals: {i18n_path: 'payments.finished.finished_payments', especific_search_path: search_ended_payments_path,
                                                  placeholder: 'Pesquisar pelo número do pedido ou cpf', search: search }%>

<section class='container-grid'>
    <% if @finished_payments.empty? %>
        <span><%= t('.no_finished_payments') %></span>
    <% else %>
        <%@finished_payments.each do |payment|%>
            <%= render partial: 'payment_info', locals: {payment: payment}%>
        <%end%>
    <% end %>
</section>

app/views/payments/_payment_info.html.erb
<%= tag.div id: payment.order_number, class: 'payment-card' do %>
  <div class='header'>
    <div>
      <h3 class='header-title'><%= t('.order') %> <%= payment.order_number %></h3>
      <h3 class='header-title'><%= I18n.localize(payment.payment_date) %></h3>
    </div>

    <% if payment.approved? %>
      <h5 class='header-status text-success'><%= t('.approved') %></h5>
    <% elsif payment.rejected? %>
      <h5 class='header-status text-danger'><%= t('.reproved') %></h5>
    <% end %>
  </div>

  
  <% if payment.pre_approved? || payment.approved? %>
    <div class='body'>
      <div class='info-area'>
        <span><%= t('.card_number') %></span>
        <span class='card-text'><%= payment.formatted_card_number %></span>
      </div>
      <div class='info-area'>
        <span><%= t('.client_cpf') %> </span>
        <span class='card-text'><%= payment.format_cpf(payment.cpf) %></span>
      </div>
      <div class='info-area'>
        <span><%= t('.total_value') %> </span>
        <span class='card-text'>R$ <%= payment.format_money(payment.total_value) %></span>
      </div>
      <div class='info-area'>
        <span><%= t('.discounts') %> </span>
        <span class='card-text'>R$ <%= payment.format_money(payment.descount_amount) %></span>
      </div>
      <div class='info-area'>
        <span><%= t('.final_value') %> </span>
        <span class='card-text'>R$ <%= payment.format_money(payment.final_value) %></span>
      </div>
      <% if payment.pre_approved? %>
        <div class='info-area'>
          <span><%= t('.balance') %> </span>
          <span class='card-text'><%= payment.check_balance(payment.card_number) %> <%= t('.points') %> </span>
        </div>
        <div class='info-area'>
          <span><%= t('.final_balance') %> </span>
          <span class='card-text'><%= payment.get_final_balance(payment) %> <%= t('.points') %></span>
        </div>
      
        <div class='btn-area'>
          <%= button_to approve_payment_path(payment.id),
              method: :patch, id: dom_id(payment), form_class: 'w-50', class: 'btn btn-success btn-payment' do
          %>
            <i class="bi bi-bag-check-fill bag-icon"></i>
            <%= t('.approve') %>
          <% end %>
          <%= button_to reprove_payment_path(payment.id),
              method: :patch, id: dom_id(payment), form_class: 'w-50', class: 'btn btn-danger btn-payment' do
          %>
            <i class="bi bi-bag-x-fill bag-icon"></i>
            <%= t('.reprove') %>
          <% end %>
        </div>
      <% end %>
    </div>
  <% elsif payment.pre_rejected? || payment.rejected? %>
    <div class='errors-area'>
      <% payment.errors_associations.each do |error|%>
        <div class='d-flex align-items-center gap-2'>
          <i class="bi bi-x text-danger"></i>
          <%= error.error_message.description %>
        </div>
      <% end %>
    </div>
    
    <% if payment.pre_rejected? %>
      <%= button_to reprove_payment_path(payment.id),
          method: :patch, class: 'btn btn-danger btn-payment' do
      %>
        <i class="bi bi-bag-x-fill bag-icon"></i>
        <%= t('.reprove') %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/payments/_pending.html.erb
<nav aria-label="breadcrumb" >
  <ol class="breadcrumb" >
    <li class="breadcrumb-item fw-bold"><%= link_to t('breadcrumb.home'), root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= t('breadcrumb.pending_payments') %></li>
  </ol>
</nav>

<%= render partial: 'shared/search_bar', locals: {i18n_path: 'payments.pending.waiting', especific_search_path: search_pending_payments_path,
                                                  placeholder: 'Pesquisar pelo número do pedido ou cpf', search: search }%>

<section id="payments">
    <div id='pre-approved-payments'>
        <h2 class='subtitle-style'><%= t('.pre_approved') %></h2>
        <% if @pre_approved.empty? %>
            <span><%= t('.no_pre_approved_payments') %></span>
        <% else %>
          <%@pre_approved.each do |payment|%>
            <%= render partial: 'payment_info', locals: {payment: payment}%>
          <%end%>
        <% end %>
  </div>

  <div id='pre-reproved-payments'>
        <h2 class='subtitle-style'><%= t('.pre_reproved') %></h2>
        <% if @pre_reproved.empty? %>
            <span><%= t('.no_pre_reproved_payments') %></span>
        <% else %>
            <%@pre_reproved.each do |payment|%>
              <%= render partial: 'payment_info', locals: {payment: payment}%>
            <%end%>
        <% end %>
    </div>
</section>

app/views/payments/finished.html.erb
<%= render partial: 'finished', locals: {finished_payments: @finished_payments, search: false }%>

app/views/payments/pending.html.erb
<%= render partial: 'pending', locals: {pre_approved: @pre_approved, pre_reproved: @pre_reproved, search: false} %>

app/views/payments/search_ended.html.erb
<%= render partial: 'finished', locals: {finished_payments: @finished_payments, search: true }%>

app/views/payments/search_pending.html.erb
<%= render partial: 'pending', locals: {pre_approved: @pre_approved, pre_reproved: @pre_reproved, search: true } %>