config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "home#index"

  resources :companies, only: [:show, :index] do
    get 'search', on: :collection
  end
  resources :company_card_types, only: [:create, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :card_types, only: [:index, :new, :create, :show, :edit, :update] do
    patch 'enable', on: :member
    patch 'disable', on: :member
  end

  resources :payments, only: [] do
    get 'search_pending', on: :collection
    get 'search_ended', on: :collection
    patch 'approve', on: :member
    patch 'reprove', on: :member
    get 'pending', on: :collection
    get 'finished', on: :collection
  end

  resources :cashback_rules, only: [:index, :new, :create, :edit, :update] do
    get 'search', on: :collection
  end

  namespace :api do
    namespace :v1 do
      resources :company_card_types, only: [:index]
      resources :extracts, only: [:index]
      resources :payments, only: [:create, :show] do
        get 'by_cpf', on: :collection, to: 'payments#all_by_cpf'
      end
      resources :cards, only: [:create, :destroy, :show] do
        delete 'block', on: :member
        patch 'activate', on: :member
        patch 'deactivate', on: :member
        post 'upgrade', on: :collection
        patch 'recharge', on: :collection, to: 'recharges#update'
      end
    end
  end
end

app/views/layouts/_flash.html.erb
<% if flash.present? %>
  <% flash_location = admin_signed_in? ? 'flash-authenticated-area' : 'flash-unauthenticated-area' %>

  <div class='d-flex flex-column <%= flash_location %>'>
    <% flash.each do |type, message| %>
      <% icon_class = 'bi bi-exclamation-diamond-fill me-2' if type == 'alert' || type == 'warning' %>
      <% icon_class = 'bi bi-check-circle-fill me-2' if type == 'notice' %>

      <div class="alert flash alert-<%= type %> alert-dismissible fade show">
        <i class="<%= icon_class %>"></i>
        <%= message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to t('.brand_name'), root_path, class: 'navbar-brand logo-style' %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
      <% if admin_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to t('.home'), root_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= t('.card') %>
            </a>
            <ul id='cards' class="dropdown-menu">
              <li><%= link_to t('.card_types'), card_types_path, class: 'dropdown-item' %></li>
              <li><%= link_to t('.new_card_type'), new_card_type_path, class: 'dropdown-item' %></li>
              <li><%= link_to t('.provide_card_types'), companies_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= t('.cashback') %>
            </a>
            <ul id='cashback' class="dropdown-menu">
              <li><%= link_to t('.cashback_rules'), cashback_rules_path, class: 'dropdown-item' %></li>
              <li><%= link_to t('.new_cashback_rule'), new_cashback_rule_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= t('.payment') %>
            </a>
            <ul id='payment' class="dropdown-menu">
              <li><%= link_to t('.pending'), pending_payments_path, class: 'dropdown-item' %></li>
              <li><%= link_to t('.finished'), finished_payments_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
        </ul>
      <% end %>

      <div id='user-menu' class="d-flex flex-row align-items-center gap-3">
        <% if admin_signed_in? %>
          <span><%= current_admin.name %></span>
          <%= button_to destroy_admin_session_path, method: :delete, class: 'btn btn-dark' do %>
            <i class="bi bi-box-arrow-right"></i>
            <%= t('.logout') %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.cards_and_payments') %></title>
    <%= favicon_link_tag 'card.ico' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
    <link href="https://unpkg.com/slim-select@latest/dist/slimselect.css" rel="stylesheet"></link>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Libre+Barcode+128+Text&display=swap" rel="stylesheet">
  </head>

  <body>
    <header><%= render 'layouts/nav' %></header>

    <main class="container my-5 position-relative">
      <%= render 'layouts/flash' %>

      <%= yield %>
    </main>
  </body>
</html>